name: Docker Scan

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    container: ghcr.io/root-de/applied-cybersecurity/scan:latest
    steps:
    - name: get SBOM
      run: syft ubuntu:latest -o json --file sbom.json
    - name: get Vulnerabilites
      run: grype sbom.json -o json --file vuln.json
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: scan
        path: ./*.json
    - name: notify listener
      run: send_script.sh
